# 配置域名和端口
server:
  port: 8080
spring:
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    cache: false
    mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:h2:mem:h2test;IGNORECASE=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
## -----------------------业务规则配置---------------------------
business:
 rules:
   updateRule:
     isActive: true
   versionRule:
     isActive: true
   insertCancelRule:
     isActive: true
